[project]
name = "djipygui"
version = "1.0.0"
description = "Visualise drone data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dearpygui>=2.0.0",
    "folium>=0.19.5",
    "pandas>=2.2.3",
]
